baseURL = 'https://dittrichlucas.github.io/'
languageCode = 'en-us'
title = 'Lucas Dittrich'
theme = 'nightfall'
enableEmoji = true
publishDir = './docs'
disqusShortname = 'ldittrich'

[params]
author = "Lucas Dittrich"
user = "dittrichlucas"
hostname = "github.io"

published = true
readingTime = true

[[params.social]]
key = 0
name = "github"
url = "https://www.github.com/dittrichlucas"
icon = "fa-brands fa-github"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/ldittrich/"
icon = "fa-brands fa-linkedin"

[[params.social]]
key = 3
name = "email"
url = "mailto:ld.dittrich@gmail.com"
icon = "fa-solid fa-envelope"

[[params.social]]
key = 4
name = "instagram"
url = "https://www.instagram.com/ldittrich"
icon = "fa-brands fa-instagram"

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"
    
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
